export const TRAVEL_GET_TRAVELS = "TRAVEL_GET_TRAVELS"
export const TRAVEL_GET_TRAVELS_STATUS = "TRAVEL_GET_TRAVELS_STATUS"
export const TRAVEL_UDPATE_STATUS_TRAVEL= "TRAVEL_GET_TRAVELS"
export const TRAVEL_STATUS = "TRAVEL_STATUS"